# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# pre-commit hooks checks file for formatting at time of git commit
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: '^templates'
  